---
- name: Demo play
  hosts: ec2:node1
  tasks:
    - name: Ping my ec2
      ansible.builtin.ping:
    - name: Print a message
      ansible.builtin.debug:
        msg: Hello World !
- name: Install Apache
  hosts: ec2:node1
  become: true
  tasks:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: latest
    - name: Start Apache
      ansible.builtin.systemd:
        name: httpd.service
        state: started
    - name: Enable Apache
      ansible.builtin.systemd:
        name: httpd.service
        enabled: true
    - name: Create index page
      ansible.builtin.copy:
        dest: "/var/www/html/index.html"
        content: <h1>Hello World !</h1>